import type { Portrait } from "~/types/portrait";

export const PORTFOLIO_ITEMS: Portrait[] = [
  {
    id: 1,
    title: "Young family",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img1.jpg",
    size: "large",
    portraitSize: "29.7 × 42 cm (11.7 × 16.5 in)",
  },
  {
    id: 2,
    title: "Severus Snape",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img2.jpg",
    size: "small",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
  {
    id: 3,
    title: "Jasmine Trinca",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img3.jpg",
    size: "small",
    portraitSize: "29.7 × 42 cm (11.7 × 16.5 in)",
  },
  {
    id: 4,
    title: "Details",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img4.jpg",
    size: "small",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
  {
    id: 5,
    title: "Boy with glass",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img5.jpg",
    size: "large",
    portraitSize: "29.7 × 42 cm (11.7 × 16.5 in)",
  },
  {
    id: 6,
    title: "Woman",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img6.jpg",
    size: "small",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
  {
    id: 7,
    title: "Couple in love",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img7.jpg",
    size: "large",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },

  {
    id: 8,
    title: "Young man",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img8.jpg",
    size: "large",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
  {
    id: 9,
    title: "Strangers",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img9.jpg",
    size: "large",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
  {
    id: 10,
    title: "Happy couple",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img10.jpg",
    size: "small",
    portraitSize: "29.7 × 42 cm (11.7 × 16.5 in)",
  },
  {
    id: 11,
    title: "A Gentle Touch",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img11.jpg",
    size: "large",
    portraitSize: "29.7 × 42 cm (11.7 × 16.5 in)",
  },
  {
    id: 12,
    title: "The Three of Us",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img12.jpg",
    size: "small",
    portraitSize: "29.7 × 42 cm (11.7 × 16.5 in)",
  },
  {
    id: 13,
    title: "Beautiful girl",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img13.jpg",
    size: "large",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
  {
    id: 14,
    title: "The Silent Guardiana",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img14.jpg",
    size: "small",
    portraitSize: "29.7 × 42 cm (11.7 × 16.5 in)",
  },
  {
    id: 15,
    title: "The King of Rock",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img15.jpg",
    size: "large",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
  {
    id: 16,
    title: "Pure Joy",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img16.jpg",
    size: "small",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
  {
    id: 17,
    title: "Best Buds",
    category: "Pencil",
    img: "/images/portfolio/portfolio_img17.jpg",
    size: "large",
    portraitSize: "21 × 29.7 cm (8.27 × 11.7 in)",
  },
];
